version : "3.8"

services:
  minio:
    image: minio/minio:latest
    environment:
      MINIO_ROOT_USER: sample-user
      MINIO_ROOT_PASSWORD: sample-password
      MINIO_DOMAIN: "s3.myserver.com" # MinIO 도메인 설정 (AWS 스타일로 운용시 필요한가봄... {가상 호스트 방식})
      MINIO_BROWSER_REDIRECT_URL: "https://s3.myserver.com" # 내부통신이 http 여도, 외부에서 https로 노출된다면, 맞춰줘야함.
      # MINIO_DOMAIN이 설정되었다면, haproxy나 nginx사용하여 라우팅 할 경우엔 "*.s3.myserver.com" 처럼 conf파일에 와일드카드 처리 필요
    ports:
      - "9000:9000" # S3 API 포트 매핑
      - "9001:9001" # MinIO 웹 콘솔 포트 매핑

    command: server /data --console-address ":9001" # MinIO 서버 시작 명령어 /data 디렉토리에 데이터를 저장하고 콘솔 주소를 9001로 설정

    restart: always # 컨테이너가 중지되면 항상 재시작
    volumes:
      - ./minio_data:/data # 현재 경로 기준 임의 데이터베이스 데이터 경로
    networks:
      - sample-custom-networksname # 사용자 정의 네트워크 이름.

networks:
  sample-custom-networksname: # 사용자 정의 네트워크 이름
    driver: bridge # 브리지 네트워크 드라이버 사용